sudo: required
before_install:
#  - sudo apt-get install libao-dev

sudo: required
  
# Enable C++ support
language: cpp

os:
  - linux
  
addons:
  apt:
     packages:
      - lcov

# Compiler selection
compiler:
  - gcc
  - clang

git:
  submodules: false

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  
  # Go to the Root directory  
  - cd ..

before_script:
  - wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz -O /tmp/sfml.tar.gz
  - tar -xvf /tmp/sfml.tar.gz
  - sudo cp -r SFML-2.4.2/* /usr/SFML
  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 libxcb-image0 libxcb-randr0 libudev1

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

# Build steps
script:
  - mkdir build && cd build
  - ${DEPS_DIR}/cmake/bin/cmake -DCOVERAGE=1 ..
  - ${DEPS_DIR}/cmake/bin/cmake --build . --target engine_physics_unit
  - ${DEPS_DIR}/cmake/bin/cmake --build . --target engine_core_unit
  - ./engine_physics_unit
  - ./engine_core_unit

after_success:
    # Creating report
  - ls ${TRAVIS_BUILD_DIR}
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
